<a href="https://colab.research.google.com/github/SorayaFrancoLopez/RN/blob/main/clasificar_emails.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Descargas de bibliotecas.
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from scipy.sparse import hstack
from google.colab import drive
from sklearn.metrics import accuracy_score

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv("/content/drive/MyDrive/e-mails.csv", delimiter=';', encoding='latin1')

In [4]:
df

emails                                       asunto  \
0     cliente1@email.com                        Solicitud de Préstamo   
1     cliente2@email.com                      Consulta de Inversiones   
2     cliente3@email.com                          Reclamo sobre Cargo   
3     cliente4@email.com              Pregunta sobre Cuenta de Ahorro   
4     cliente5@email.com                    Actualización de Contacto   
..                   ...                                          ...   
95   cliente96@email.com  Solicitud de Tarjeta de Crédito Empresarial   
96   cliente97@email.com          Problema con Transferencia Bancaria   
97   cliente98@email.com                  Informe de Estado de Cuenta   
98   cliente99@email.com                      Pregunta sobre Hipoteca   
99  cliente100@email.com          Solicitud de Préstamo para Estudios   

                                                texto prioridad  
0   Hola, necesito solicitar un préstamo para una ...      Alta  
1   Estimado Gestor, ¿cuáles son las opciones de i...     Media  
2   He notado un cargo incorrecto en mi cuenta, ¿p...      Alta  
3   Quiero saber cuál es la tasa de interés actual...      Baja  
4   Estimado Gestor, he cambiado mi dirección y nú...     Media  
..                                                ...       ...  
95  Quiero solicitar una tarjeta de crédito empres...      Alta  
96  He tenido un problema con una transferencia ba...      Alta  
97  ¿Puedes proporcionarme una copia de mi estado ...     Media  
98  Estimado Gestor, necesito información sobre la...      Baja  
99  Quiero solicitar un préstamo para financiar mi...      Alta  

[100 rows x 4 columns]

In [5]:
# Vectorización del campo 'texto'
text_vectorizer = TfidfVectorizer(max_features=50)
X_text = text_vectorizer.fit_transform(df['texto'])

# Vectorización del campo 'asunto'
subject_vectorizer = TfidfVectorizer(max_features=50)
X_subject = subject_vectorizer.fit_transform(df['asunto'])

# Combinar las dos representaciones TF-IDF
X_combined = hstack([X_text, X_subject])

In [9]:
dense_X_combined = X_combined.toarray()

In [10]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['prioridad'])

In [11]:
encoder = OneHotEncoder(sparse=False)
dense_X_combined_onehot = encoder.fit_transform(dense_X_combined)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [12]:
#division en train y test
X_train, X_test, y_train, y_test = train_test_split(dense_X_combined_onehot, y, test_size=0.2, random_state=42)

In [13]:
X_train

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [14]:
X_test

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [15]:
y_train

array([0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 1, 2,
       1, 0, 1, 1, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 0, 0, 2, 1,
       0, 1, 2, 2, 2, 2, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 2, 0,
       2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2])

In [16]:
y_test

array([1, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 1, 0, 2])

In [17]:
y_train_onehot = tf.one_hot(y_train, depth=3)

In [18]:
model = keras.Sequential([
    keras.layers.Dense(64, input_shape=(676,), activation='relu'),  # Ajusta 100 al número de características en X_combined
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(3, activation='softmax')  # 3 clases de prioridad
])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train_onehot, epochs=10, batch_size=32)

Epoch 1/10
3/3 [==============================] - 1s 10ms/step - loss: 1.1178 - accuracy: 0.3250
Epoch 2/10
3/3 [==============================] - 0s 8ms/step - loss: 0.9662 - accuracy: 0.5625
Epoch 3/10
3/3 [==============================] - 0s 6ms/step - loss: 0.8749 - accuracy: 0.7000
Epoch 4/10
3/3 [==============================] - 0s 6ms/step - loss: 0.7873 - accuracy: 0.8125
Epoch 5/10
3/3 [==============================] - 0s 9ms/step - loss: 0.7028 - accuracy: 0.8625
Epoch 6/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6201 - accuracy: 0.8500
Epoch 7/10
3/3 [==============================] - 0s 6ms/step - loss: 0.5440 - accuracy: 0.8875
Epoch 8/10
3/3 [==============================] - 0s 5ms/step - loss: 0.4729 - accuracy: 0.9250
Epoch 9/10
3/3 [==============================] - 0s 8ms/step - loss: 0.4007 - accuracy: 0.9500
Epoch 10/10
3/3 [==============================] - 0s 7ms/step - loss: 0.3436 - accuracy: 0.9500


In [19]:
y_pred = model.predict(X_test)

# Convertir las probabilidades en etiquetas predichas (la clase con la probabilidad más alta)
y_pred_classes = np.argmax(y_pred, axis=1)

# Calcular la precisión
accuracy = accuracy_score(y_test, y_pred_classes)

print(f'Precisión del modelo en el conjunto de prueba: {accuracy * 100:.2f}%')

1/1 [==============================] - 0s 129ms/step
Precisión del modelo en el conjunto de prueba: 75.00%


In [20]:
model.save('Kai_correos.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [21]:
"""from tensorflow import keras

# Cargar el modelo desde el archivo
loaded_model = keras.models.load_model('modelo_entrenado.h5')

# Aquí debes tener tus datos de entrada, por ejemplo, X_input
# Realizar predicciones
predictions = loaded_model.predict(X_input)

# El resultado en 'predictions' contendrá las probabilidades para cada clase
# Puedes convertir las probabilidades en etiquetas predichas si es necesario
predicted_classes = predictions.argmax(axis=-1)

# Ahora 'predicted_classes' contiene las etiquetas predichas"""


"from tensorflow import keras\n\n# Cargar el modelo desde el archivo\nloaded_model = keras.models.load_model('modelo_entrenado.h5')\n\n# Aquí debes tener tus datos de entrada, por ejemplo, X_input\n# Realizar predicciones\npredictions = loaded_model.predict(X_input)\n\n# El resultado en 'predictions' contendrá las probabilidades para cada clase\n# Puedes convertir las probabilidades en etiquetas predichas si es necesario\npredicted_classes = predictions.argmax(axis=-1)\n\n# Ahora 'predicted_classes' contiene las etiquetas predichas"